services:
  python-rag-app:
    build:
        # context starts in root folder
        context: ../../
        dockerfile: docker/dev/python/Dockerfile
    volumes:
      - ../../:/python-app
    working_dir: /python-app/python-app
    command: sh -c "uv sync --locked && sleep infinity"
    ports:
      - "8002:8002"